version: '2'
services:
    web_app:
        build: .
        container_name: "aplicacao"
        volumes:
          - ./app:/var/www/html/
        ports:
          - "80:80"
        restart: always
        depends_on:
          - db
    db:
        image: mysql:5.7
        container_name: "Banco-de-Dados"
        volumes:
        - ./sql-scripts:/docker-entrypoint-initdb.d/
        ports:
          - "0.0.0.0:3306:3306"
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: fdNF7E6hGNYcERP2
          MYSQL_DATABASE: nts_saude
